# send request to get user data with the expiring Access Token
GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obm55IiwiaWF0IjoxNjQwNTc1NzIyLCJleHAiOjE2NDA1NzU3Mzd9.GX2KVZp-Dc6bePBBBwHbtLFcIMvuYInP_F1cU7fbBzU

###

# deletes Refresh Token
DELETE http://localhost:9000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obm55IiwiaWF0IjoxNjQwNTc1Njk5fQ.rnrtIHK9oy7ViDkHSDQDssHWMksYYINzOsbNvgao1j8"
}

###

# Creates expiring Access Tokens using Refresh Token
POST http://localhost:9000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obm55IiwiaWF0IjoxNjQwNTc1Njk5fQ.rnrtIHK9oy7ViDkHSDQDssHWMksYYINzOsbNvgao1j8"
}

###

# gets the Access Token and Refresh Token
POST http://localhost:9000/login
Content-Type: application/json

{
    "username": "Johnny"
}